#!/bin/zsh

echo "===== Start cleaning temporary files and cache ====="

# Display disk space usage before cleanup
echo "Disk space usage before cleanup:"
du -sh .

# Delete CMake cache and intermediate files
echo "===== Delete CMake cache and intermediate files ====="
rm -rf CMakeFiles
rm -rf build/CMakeFiles
rm -f CMakeCache.txt
rm -f build/CMakeCache.txt
rm -f cmake_install.cmake
rm -f build/cmake_install.cmake
rm -f Makefile
rm -f build/Makefile

# Delete intermediate files and object files generated by compilation
echo "===== Delete intermediate files and object files generated by compilation ====="
find . -name "*.o" -delete
find . -name "*.obj" -delete
find . -name "*.d" -delete

# Clean Emscripten cache (Note: this may cause some files to be re-downloaded on next build)
echo "===== Clean Emscripten cache ====="
# First set Emscripten environment variables to get cache path
source ./emsdk/emsdk_env.sh
if [[ -d "$EM_CACHE" ]]; then
  echo "Found Emscripten cache directory: $EM_CACHE"
  # Clean cache while preserving necessary system files
  find "$EM_CACHE" -name "tmp*" -type d -exec rm -rf {} \; 2>/dev/null || true
  find "$EM_CACHE" -name "emscripten_temp" -type d -exec rm -rf {} \; 2>/dev/null || true
  find "$EM_CACHE" -name "cache" -type d -exec rm -rf {} \; 2>/dev/null || true
else
  echo "Emscripten cache directory not found"
fi

# Keep final build output files but delete intermediate files
echo "===== Keep final build output, delete intermediate files ====="
# Save current wasm and js files if needed
if [[ -f "satpath.js" && -f "satpath.wasm" ]]; then
  echo "Save current satpath.js and satpath.wasm files"
  if [[ ! -d "build" ]]; then
    mkdir -p build
  fi
  cp satpath.js build/ 2>/dev/null || true
  cp satpath.wasm build/ 2>/dev/null || true
fi

# Delete temporary files from emsdk downloads
echo "===== Clean emsdk download cache ====="
rm -rf ./emsdk/downloads/*.tmp
find ./emsdk/downloads -name "*.zip" -delete
find ./emsdk/downloads -name "*.tar.gz" -delete
find ./emsdk/downloads -name "*.tar.xz" -delete

# Display disk space usage after cleanup
echo "===== Cleanup completed ====="
echo "Disk space usage after cleanup:"
du -sh .

echo "===== Cleanup process finished ====="
