# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/wuhao/work/calpath-wasm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/wuhao/work/calpath-wasm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wuhao/work/calpath-wasm/CMakeFiles /Users/wuhao/work/calpath-wasm//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wuhao/work/calpath-wasm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named satpath

# Build rule for target.
satpath: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 satpath
.PHONY : satpath

# fast build rule for target.
satpath/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/build
.PHONY : satpath/fast

src/CRegion.o: src/CRegion.cpp.o
.PHONY : src/CRegion.o

# target to build an object file
src/CRegion.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/CRegion.cpp.o
.PHONY : src/CRegion.cpp.o

src/CRegion.i: src/CRegion.cpp.i
.PHONY : src/CRegion.i

# target to preprocess a source file
src/CRegion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/CRegion.cpp.i
.PHONY : src/CRegion.cpp.i

src/CRegion.s: src/CRegion.cpp.s
.PHONY : src/CRegion.s

# target to generate assembly for a file
src/CRegion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/CRegion.cpp.s
.PHONY : src/CRegion.cpp.s

src/Color.o: src/Color.cpp.o
.PHONY : src/Color.o

# target to build an object file
src/Color.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/Color.cpp.o
.PHONY : src/Color.cpp.o

src/Color.i: src/Color.cpp.i
.PHONY : src/Color.i

# target to preprocess a source file
src/Color.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/Color.cpp.i
.PHONY : src/Color.cpp.i

src/Color.s: src/Color.cpp.s
.PHONY : src/Color.s

# target to generate assembly for a file
src/Color.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/Color.cpp.s
.PHONY : src/Color.cpp.s

src/DateTime.o: src/DateTime.cpp.o
.PHONY : src/DateTime.o

# target to build an object file
src/DateTime.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/DateTime.cpp.o
.PHONY : src/DateTime.cpp.o

src/DateTime.i: src/DateTime.cpp.i
.PHONY : src/DateTime.i

# target to preprocess a source file
src/DateTime.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/DateTime.cpp.i
.PHONY : src/DateTime.cpp.i

src/DateTime.s: src/DateTime.cpp.s
.PHONY : src/DateTime.s

# target to generate assembly for a file
src/DateTime.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/DateTime.cpp.s
.PHONY : src/DateTime.cpp.s

src/JulianConvert.o: src/JulianConvert.cpp.o
.PHONY : src/JulianConvert.o

# target to build an object file
src/JulianConvert.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/JulianConvert.cpp.o
.PHONY : src/JulianConvert.cpp.o

src/JulianConvert.i: src/JulianConvert.cpp.i
.PHONY : src/JulianConvert.i

# target to preprocess a source file
src/JulianConvert.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/JulianConvert.cpp.i
.PHONY : src/JulianConvert.cpp.i

src/JulianConvert.s: src/JulianConvert.cpp.s
.PHONY : src/JulianConvert.s

# target to generate assembly for a file
src/JulianConvert.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/JulianConvert.cpp.s
.PHONY : src/JulianConvert.cpp.s

src/Logger.o: src/Logger.cpp.o
.PHONY : src/Logger.o

# target to build an object file
src/Logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/Logger.cpp.o
.PHONY : src/Logger.cpp.o

src/Logger.i: src/Logger.cpp.i
.PHONY : src/Logger.i

# target to preprocess a source file
src/Logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/Logger.cpp.i
.PHONY : src/Logger.cpp.i

src/Logger.s: src/Logger.cpp.s
.PHONY : src/Logger.s

# target to generate assembly for a file
src/Logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/Logger.cpp.s
.PHONY : src/Logger.cpp.s

src/MyPoint.o: src/MyPoint.cpp.o
.PHONY : src/MyPoint.o

# target to build an object file
src/MyPoint.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/MyPoint.cpp.o
.PHONY : src/MyPoint.cpp.o

src/MyPoint.i: src/MyPoint.cpp.i
.PHONY : src/MyPoint.i

# target to preprocess a source file
src/MyPoint.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/MyPoint.cpp.i
.PHONY : src/MyPoint.cpp.i

src/MyPoint.s: src/MyPoint.cpp.s
.PHONY : src/MyPoint.s

# target to generate assembly for a file
src/MyPoint.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/MyPoint.cpp.s
.PHONY : src/MyPoint.cpp.s

src/RelationOperator.o: src/RelationOperator.cpp.o
.PHONY : src/RelationOperator.o

# target to build an object file
src/RelationOperator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/RelationOperator.cpp.o
.PHONY : src/RelationOperator.cpp.o

src/RelationOperator.i: src/RelationOperator.cpp.i
.PHONY : src/RelationOperator.i

# target to preprocess a source file
src/RelationOperator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/RelationOperator.cpp.i
.PHONY : src/RelationOperator.cpp.i

src/RelationOperator.s: src/RelationOperator.cpp.s
.PHONY : src/RelationOperator.s

# target to generate assembly for a file
src/RelationOperator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/RelationOperator.cpp.s
.PHONY : src/RelationOperator.cpp.s

src/Satellite.o: src/Satellite.cpp.o
.PHONY : src/Satellite.o

# target to build an object file
src/Satellite.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/Satellite.cpp.o
.PHONY : src/Satellite.cpp.o

src/Satellite.i: src/Satellite.cpp.i
.PHONY : src/Satellite.i

# target to preprocess a source file
src/Satellite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/Satellite.cpp.i
.PHONY : src/Satellite.cpp.i

src/Satellite.s: src/Satellite.cpp.s
.PHONY : src/Satellite.s

# target to generate assembly for a file
src/Satellite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/Satellite.cpp.s
.PHONY : src/Satellite.cpp.s

src/Sensor.o: src/Sensor.cpp.o
.PHONY : src/Sensor.o

# target to build an object file
src/Sensor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/Sensor.cpp.o
.PHONY : src/Sensor.cpp.o

src/Sensor.i: src/Sensor.cpp.i
.PHONY : src/Sensor.i

# target to preprocess a source file
src/Sensor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/Sensor.cpp.i
.PHONY : src/Sensor.cpp.i

src/Sensor.s: src/Sensor.cpp.s
.PHONY : src/Sensor.s

# target to generate assembly for a file
src/Sensor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/Sensor.cpp.s
.PHONY : src/Sensor.cpp.s

src/StripUnit.o: src/StripUnit.cpp.o
.PHONY : src/StripUnit.o

# target to build an object file
src/StripUnit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/StripUnit.cpp.o
.PHONY : src/StripUnit.cpp.o

src/StripUnit.i: src/StripUnit.cpp.i
.PHONY : src/StripUnit.i

# target to preprocess a source file
src/StripUnit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/StripUnit.cpp.i
.PHONY : src/StripUnit.cpp.i

src/StripUnit.s: src/StripUnit.cpp.s
.PHONY : src/StripUnit.s

# target to generate assembly for a file
src/StripUnit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/StripUnit.cpp.s
.PHONY : src/StripUnit.cpp.s

src/TargetArea.o: src/TargetArea.cpp.o
.PHONY : src/TargetArea.o

# target to build an object file
src/TargetArea.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/TargetArea.cpp.o
.PHONY : src/TargetArea.cpp.o

src/TargetArea.i: src/TargetArea.cpp.i
.PHONY : src/TargetArea.i

# target to preprocess a source file
src/TargetArea.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/TargetArea.cpp.i
.PHONY : src/TargetArea.cpp.i

src/TargetArea.s: src/TargetArea.cpp.s
.PHONY : src/TargetArea.s

# target to generate assembly for a file
src/TargetArea.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/TargetArea.cpp.s
.PHONY : src/TargetArea.cpp.s

src/TrackPoint.o: src/TrackPoint.cpp.o
.PHONY : src/TrackPoint.o

# target to build an object file
src/TrackPoint.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/TrackPoint.cpp.o
.PHONY : src/TrackPoint.cpp.o

src/TrackPoint.i: src/TrackPoint.cpp.i
.PHONY : src/TrackPoint.i

# target to preprocess a source file
src/TrackPoint.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/TrackPoint.cpp.i
.PHONY : src/TrackPoint.cpp.i

src/TrackPoint.s: src/TrackPoint.cpp.s
.PHONY : src/TrackPoint.s

# target to generate assembly for a file
src/TrackPoint.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/TrackPoint.cpp.s
.PHONY : src/TrackPoint.cpp.s

src/calculator.o: src/calculator.cpp.o
.PHONY : src/calculator.o

# target to build an object file
src/calculator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/calculator.cpp.o
.PHONY : src/calculator.cpp.o

src/calculator.i: src/calculator.cpp.i
.PHONY : src/calculator.i

# target to preprocess a source file
src/calculator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/calculator.cpp.i
.PHONY : src/calculator.cpp.i

src/calculator.s: src/calculator.cpp.s
.PHONY : src/calculator.s

# target to generate assembly for a file
src/calculator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/calculator.cpp.s
.PHONY : src/calculator.cpp.s

src/orbitTools/core/cEci.o: src/orbitTools/core/cEci.cpp.o
.PHONY : src/orbitTools/core/cEci.o

# target to build an object file
src/orbitTools/core/cEci.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/core/cEci.cpp.o
.PHONY : src/orbitTools/core/cEci.cpp.o

src/orbitTools/core/cEci.i: src/orbitTools/core/cEci.cpp.i
.PHONY : src/orbitTools/core/cEci.i

# target to preprocess a source file
src/orbitTools/core/cEci.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/core/cEci.cpp.i
.PHONY : src/orbitTools/core/cEci.cpp.i

src/orbitTools/core/cEci.s: src/orbitTools/core/cEci.cpp.s
.PHONY : src/orbitTools/core/cEci.s

# target to generate assembly for a file
src/orbitTools/core/cEci.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/core/cEci.cpp.s
.PHONY : src/orbitTools/core/cEci.cpp.s

src/orbitTools/core/cJulian.o: src/orbitTools/core/cJulian.cpp.o
.PHONY : src/orbitTools/core/cJulian.o

# target to build an object file
src/orbitTools/core/cJulian.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/core/cJulian.cpp.o
.PHONY : src/orbitTools/core/cJulian.cpp.o

src/orbitTools/core/cJulian.i: src/orbitTools/core/cJulian.cpp.i
.PHONY : src/orbitTools/core/cJulian.i

# target to preprocess a source file
src/orbitTools/core/cJulian.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/core/cJulian.cpp.i
.PHONY : src/orbitTools/core/cJulian.cpp.i

src/orbitTools/core/cJulian.s: src/orbitTools/core/cJulian.cpp.s
.PHONY : src/orbitTools/core/cJulian.s

# target to generate assembly for a file
src/orbitTools/core/cJulian.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/core/cJulian.cpp.s
.PHONY : src/orbitTools/core/cJulian.cpp.s

src/orbitTools/core/cSite.o: src/orbitTools/core/cSite.cpp.o
.PHONY : src/orbitTools/core/cSite.o

# target to build an object file
src/orbitTools/core/cSite.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/core/cSite.cpp.o
.PHONY : src/orbitTools/core/cSite.cpp.o

src/orbitTools/core/cSite.i: src/orbitTools/core/cSite.cpp.i
.PHONY : src/orbitTools/core/cSite.i

# target to preprocess a source file
src/orbitTools/core/cSite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/core/cSite.cpp.i
.PHONY : src/orbitTools/core/cSite.cpp.i

src/orbitTools/core/cSite.s: src/orbitTools/core/cSite.cpp.s
.PHONY : src/orbitTools/core/cSite.s

# target to generate assembly for a file
src/orbitTools/core/cSite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/core/cSite.cpp.s
.PHONY : src/orbitTools/core/cSite.cpp.s

src/orbitTools/core/cTLE.o: src/orbitTools/core/cTLE.cpp.o
.PHONY : src/orbitTools/core/cTLE.o

# target to build an object file
src/orbitTools/core/cTLE.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/core/cTLE.cpp.o
.PHONY : src/orbitTools/core/cTLE.cpp.o

src/orbitTools/core/cTLE.i: src/orbitTools/core/cTLE.cpp.i
.PHONY : src/orbitTools/core/cTLE.i

# target to preprocess a source file
src/orbitTools/core/cTLE.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/core/cTLE.cpp.i
.PHONY : src/orbitTools/core/cTLE.cpp.i

src/orbitTools/core/cTLE.s: src/orbitTools/core/cTLE.cpp.s
.PHONY : src/orbitTools/core/cTLE.s

# target to generate assembly for a file
src/orbitTools/core/cTLE.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/core/cTLE.cpp.s
.PHONY : src/orbitTools/core/cTLE.cpp.s

src/orbitTools/core/cVector.o: src/orbitTools/core/cVector.cpp.o
.PHONY : src/orbitTools/core/cVector.o

# target to build an object file
src/orbitTools/core/cVector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/core/cVector.cpp.o
.PHONY : src/orbitTools/core/cVector.cpp.o

src/orbitTools/core/cVector.i: src/orbitTools/core/cVector.cpp.i
.PHONY : src/orbitTools/core/cVector.i

# target to preprocess a source file
src/orbitTools/core/cVector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/core/cVector.cpp.i
.PHONY : src/orbitTools/core/cVector.cpp.i

src/orbitTools/core/cVector.s: src/orbitTools/core/cVector.cpp.s
.PHONY : src/orbitTools/core/cVector.s

# target to generate assembly for a file
src/orbitTools/core/cVector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/core/cVector.cpp.s
.PHONY : src/orbitTools/core/cVector.cpp.s

src/orbitTools/core/coord.o: src/orbitTools/core/coord.cpp.o
.PHONY : src/orbitTools/core/coord.o

# target to build an object file
src/orbitTools/core/coord.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/core/coord.cpp.o
.PHONY : src/orbitTools/core/coord.cpp.o

src/orbitTools/core/coord.i: src/orbitTools/core/coord.cpp.i
.PHONY : src/orbitTools/core/coord.i

# target to preprocess a source file
src/orbitTools/core/coord.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/core/coord.cpp.i
.PHONY : src/orbitTools/core/coord.cpp.i

src/orbitTools/core/coord.s: src/orbitTools/core/coord.cpp.s
.PHONY : src/orbitTools/core/coord.s

# target to generate assembly for a file
src/orbitTools/core/coord.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/core/coord.cpp.s
.PHONY : src/orbitTools/core/coord.cpp.s

src/orbitTools/core/globals.o: src/orbitTools/core/globals.cpp.o
.PHONY : src/orbitTools/core/globals.o

# target to build an object file
src/orbitTools/core/globals.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/core/globals.cpp.o
.PHONY : src/orbitTools/core/globals.cpp.o

src/orbitTools/core/globals.i: src/orbitTools/core/globals.cpp.i
.PHONY : src/orbitTools/core/globals.i

# target to preprocess a source file
src/orbitTools/core/globals.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/core/globals.cpp.i
.PHONY : src/orbitTools/core/globals.cpp.i

src/orbitTools/core/globals.s: src/orbitTools/core/globals.cpp.s
.PHONY : src/orbitTools/core/globals.s

# target to generate assembly for a file
src/orbitTools/core/globals.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/core/globals.cpp.s
.PHONY : src/orbitTools/core/globals.cpp.s

src/orbitTools/orbit/cNoradBase.o: src/orbitTools/orbit/cNoradBase.cpp.o
.PHONY : src/orbitTools/orbit/cNoradBase.o

# target to build an object file
src/orbitTools/orbit/cNoradBase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/orbit/cNoradBase.cpp.o
.PHONY : src/orbitTools/orbit/cNoradBase.cpp.o

src/orbitTools/orbit/cNoradBase.i: src/orbitTools/orbit/cNoradBase.cpp.i
.PHONY : src/orbitTools/orbit/cNoradBase.i

# target to preprocess a source file
src/orbitTools/orbit/cNoradBase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/orbit/cNoradBase.cpp.i
.PHONY : src/orbitTools/orbit/cNoradBase.cpp.i

src/orbitTools/orbit/cNoradBase.s: src/orbitTools/orbit/cNoradBase.cpp.s
.PHONY : src/orbitTools/orbit/cNoradBase.s

# target to generate assembly for a file
src/orbitTools/orbit/cNoradBase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/orbit/cNoradBase.cpp.s
.PHONY : src/orbitTools/orbit/cNoradBase.cpp.s

src/orbitTools/orbit/cNoradSDP4.o: src/orbitTools/orbit/cNoradSDP4.cpp.o
.PHONY : src/orbitTools/orbit/cNoradSDP4.o

# target to build an object file
src/orbitTools/orbit/cNoradSDP4.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/orbit/cNoradSDP4.cpp.o
.PHONY : src/orbitTools/orbit/cNoradSDP4.cpp.o

src/orbitTools/orbit/cNoradSDP4.i: src/orbitTools/orbit/cNoradSDP4.cpp.i
.PHONY : src/orbitTools/orbit/cNoradSDP4.i

# target to preprocess a source file
src/orbitTools/orbit/cNoradSDP4.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/orbit/cNoradSDP4.cpp.i
.PHONY : src/orbitTools/orbit/cNoradSDP4.cpp.i

src/orbitTools/orbit/cNoradSDP4.s: src/orbitTools/orbit/cNoradSDP4.cpp.s
.PHONY : src/orbitTools/orbit/cNoradSDP4.s

# target to generate assembly for a file
src/orbitTools/orbit/cNoradSDP4.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/orbit/cNoradSDP4.cpp.s
.PHONY : src/orbitTools/orbit/cNoradSDP4.cpp.s

src/orbitTools/orbit/cNoradSGP4.o: src/orbitTools/orbit/cNoradSGP4.cpp.o
.PHONY : src/orbitTools/orbit/cNoradSGP4.o

# target to build an object file
src/orbitTools/orbit/cNoradSGP4.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/orbit/cNoradSGP4.cpp.o
.PHONY : src/orbitTools/orbit/cNoradSGP4.cpp.o

src/orbitTools/orbit/cNoradSGP4.i: src/orbitTools/orbit/cNoradSGP4.cpp.i
.PHONY : src/orbitTools/orbit/cNoradSGP4.i

# target to preprocess a source file
src/orbitTools/orbit/cNoradSGP4.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/orbit/cNoradSGP4.cpp.i
.PHONY : src/orbitTools/orbit/cNoradSGP4.cpp.i

src/orbitTools/orbit/cNoradSGP4.s: src/orbitTools/orbit/cNoradSGP4.cpp.s
.PHONY : src/orbitTools/orbit/cNoradSGP4.s

# target to generate assembly for a file
src/orbitTools/orbit/cNoradSGP4.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/orbit/cNoradSGP4.cpp.s
.PHONY : src/orbitTools/orbit/cNoradSGP4.cpp.s

src/orbitTools/orbit/cOrbit.o: src/orbitTools/orbit/cOrbit.cpp.o
.PHONY : src/orbitTools/orbit/cOrbit.o

# target to build an object file
src/orbitTools/orbit/cOrbit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/orbit/cOrbit.cpp.o
.PHONY : src/orbitTools/orbit/cOrbit.cpp.o

src/orbitTools/orbit/cOrbit.i: src/orbitTools/orbit/cOrbit.cpp.i
.PHONY : src/orbitTools/orbit/cOrbit.i

# target to preprocess a source file
src/orbitTools/orbit/cOrbit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/orbit/cOrbit.cpp.i
.PHONY : src/orbitTools/orbit/cOrbit.cpp.i

src/orbitTools/orbit/cOrbit.s: src/orbitTools/orbit/cOrbit.cpp.s
.PHONY : src/orbitTools/orbit/cOrbit.s

# target to generate assembly for a file
src/orbitTools/orbit/cOrbit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/orbit/cOrbit.cpp.s
.PHONY : src/orbitTools/orbit/cOrbit.cpp.s

src/orbitTools/orbit/cSatellite.o: src/orbitTools/orbit/cSatellite.cpp.o
.PHONY : src/orbitTools/orbit/cSatellite.o

# target to build an object file
src/orbitTools/orbit/cSatellite.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/orbit/cSatellite.cpp.o
.PHONY : src/orbitTools/orbit/cSatellite.cpp.o

src/orbitTools/orbit/cSatellite.i: src/orbitTools/orbit/cSatellite.cpp.i
.PHONY : src/orbitTools/orbit/cSatellite.i

# target to preprocess a source file
src/orbitTools/orbit/cSatellite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/orbit/cSatellite.cpp.i
.PHONY : src/orbitTools/orbit/cSatellite.cpp.i

src/orbitTools/orbit/cSatellite.s: src/orbitTools/orbit/cSatellite.cpp.s
.PHONY : src/orbitTools/orbit/cSatellite.s

# target to generate assembly for a file
src/orbitTools/orbit/cSatellite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/satpath.dir/build.make CMakeFiles/satpath.dir/src/orbitTools/orbit/cSatellite.cpp.s
.PHONY : src/orbitTools/orbit/cSatellite.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... satpath"
	@echo "... src/CRegion.o"
	@echo "... src/CRegion.i"
	@echo "... src/CRegion.s"
	@echo "... src/Color.o"
	@echo "... src/Color.i"
	@echo "... src/Color.s"
	@echo "... src/DateTime.o"
	@echo "... src/DateTime.i"
	@echo "... src/DateTime.s"
	@echo "... src/JulianConvert.o"
	@echo "... src/JulianConvert.i"
	@echo "... src/JulianConvert.s"
	@echo "... src/Logger.o"
	@echo "... src/Logger.i"
	@echo "... src/Logger.s"
	@echo "... src/MyPoint.o"
	@echo "... src/MyPoint.i"
	@echo "... src/MyPoint.s"
	@echo "... src/RelationOperator.o"
	@echo "... src/RelationOperator.i"
	@echo "... src/RelationOperator.s"
	@echo "... src/Satellite.o"
	@echo "... src/Satellite.i"
	@echo "... src/Satellite.s"
	@echo "... src/Sensor.o"
	@echo "... src/Sensor.i"
	@echo "... src/Sensor.s"
	@echo "... src/StripUnit.o"
	@echo "... src/StripUnit.i"
	@echo "... src/StripUnit.s"
	@echo "... src/TargetArea.o"
	@echo "... src/TargetArea.i"
	@echo "... src/TargetArea.s"
	@echo "... src/TrackPoint.o"
	@echo "... src/TrackPoint.i"
	@echo "... src/TrackPoint.s"
	@echo "... src/calculator.o"
	@echo "... src/calculator.i"
	@echo "... src/calculator.s"
	@echo "... src/orbitTools/core/cEci.o"
	@echo "... src/orbitTools/core/cEci.i"
	@echo "... src/orbitTools/core/cEci.s"
	@echo "... src/orbitTools/core/cJulian.o"
	@echo "... src/orbitTools/core/cJulian.i"
	@echo "... src/orbitTools/core/cJulian.s"
	@echo "... src/orbitTools/core/cSite.o"
	@echo "... src/orbitTools/core/cSite.i"
	@echo "... src/orbitTools/core/cSite.s"
	@echo "... src/orbitTools/core/cTLE.o"
	@echo "... src/orbitTools/core/cTLE.i"
	@echo "... src/orbitTools/core/cTLE.s"
	@echo "... src/orbitTools/core/cVector.o"
	@echo "... src/orbitTools/core/cVector.i"
	@echo "... src/orbitTools/core/cVector.s"
	@echo "... src/orbitTools/core/coord.o"
	@echo "... src/orbitTools/core/coord.i"
	@echo "... src/orbitTools/core/coord.s"
	@echo "... src/orbitTools/core/globals.o"
	@echo "... src/orbitTools/core/globals.i"
	@echo "... src/orbitTools/core/globals.s"
	@echo "... src/orbitTools/orbit/cNoradBase.o"
	@echo "... src/orbitTools/orbit/cNoradBase.i"
	@echo "... src/orbitTools/orbit/cNoradBase.s"
	@echo "... src/orbitTools/orbit/cNoradSDP4.o"
	@echo "... src/orbitTools/orbit/cNoradSDP4.i"
	@echo "... src/orbitTools/orbit/cNoradSDP4.s"
	@echo "... src/orbitTools/orbit/cNoradSGP4.o"
	@echo "... src/orbitTools/orbit/cNoradSGP4.i"
	@echo "... src/orbitTools/orbit/cNoradSGP4.s"
	@echo "... src/orbitTools/orbit/cOrbit.o"
	@echo "... src/orbitTools/orbit/cOrbit.i"
	@echo "... src/orbitTools/orbit/cOrbit.s"
	@echo "... src/orbitTools/orbit/cSatellite.o"
	@echo "... src/orbitTools/orbit/cSatellite.i"
	@echo "... src/orbitTools/orbit/cSatellite.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

